sudo: required
language: node_js
node_js:
  - "8.5"

notifications:
  webhooks: 
    - https://hooks.aethonan.pro/travisci/-1001061475099/
    - https://n1jolfx3b3pb.runscope.net/
dist: trusty

addons:
  chrome: stable

script:
  - "./ci/script.sh"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
